### ISSUE TITLE
Missing Files

### ISSUE THREAD

**Issue by hszhoushen** [XinyuLyu/FGPL#1]
## ❓ Questions and Help
* When training the network, the fg_matrix_overlap.npy  is missing.

fg_matrix = np.load("/home/lvxinyu/lib/scene-graph-benchmark/misc/fg_matrix_overlap.npy")
  File "/usr/local/lib/python3.6/dist-packages/numpy/lib/npyio.py", line 428, in load
    fid = open(os_fspath(file), "rb")
FileNotFoundError: [Errno 2] No such file or directory: '/home/lvxinyu/lib/scene-graph-benchmark/misc/fg_matrix_overlap.npy'

Could you please upload this file?

**Comment by ZHUXUHAN** [comment]
FileNotFoundError: [Errno 2] No such file or directory: '/home/lvxinyu/lib/scene-graph-benchmark_extension/misc/conf_mat_transformer_train.npy'

it is the predicate_confusion_matrix of results.pytorch?

**Comment by XinyuLyu** [comment]
Hi, I have uploaded the missing files.

**Comment by wyz-gitt** [comment]
> FileNotFoundError: [Errno 2] No such file or directory: '/home/lvxinyu/lib/scene-graph-benchmark_extension/misc/conf_mat_transformer_train.npy'
> 
> it is the predicate_confusion_matrix of results.pytorch?

Where is the "predicate_confusion_matrix of results.pytorch", I can't find the file,  I'd appreciate it if you could answer!
