### ISSUE TITLE
How to obtain the Predicate Lattice in the paper?

### ISSUE THREAD

**Issue by Qi-Chuan** [XinyuLyu/FGPL#2]
## ❓ Questions and Help
One important step is to obtain the Predicate Lattice, in other words, to extract baselines' confusion matrix from their biased prediction trained with freq bias. Could you please upload the code of this part? Thanks a lot !

**Comment by XinyuLyu** [comment]
Hi, actually this part of codes, extracting confusion matrix from their biased prediction trained with freq bias, has been published in this repositories. You need train a Baseline SGG model with freq-bias (i.e., Transformer, Motif and VCTree) from scratch by relation_train_net.py (without using our FGPL). Then, obtain the biased predictions by relation_test_net.py. After finishing the training session, the confusion matrix can be derived in saved *.pytorch as self.result_dict['predicate_confusion_matrix'] (refer to sgg_eval,py).

**Comment by wyz-gitt** [comment]
> Hi, actually this part of codes, extracting confusion matrix from their biased prediction trained with freq bias, has been published in this repositories. You need train a Baseline SGG model with freq-bias (i.e., Transformer, Motif and VCTree) from scratch by relation_train_net.py (without using our FGPL). Then, obtain the biased predictions by relation_test_net.py. After finishing the training session, the confusion matrix can be derived in saved *.pytorch as self.result_dict['predicate_confusion_matrix'] (refer to sgg_eval,py).
Hello, how can I read the content from *.pytorch? Can you provide your script, thanks a lot!
